type Mutation {
	addScience(
		identifier: String!
		presences: [String]
		os: String
		arch: String
	): AddScienceResult
}

type AddScienceResult {
	identifier: String
	presences: [String]
	os: String
	arch: String
}
