query contributors {
	credits {
		user {
			id
			name
			avatar
			roleId
			role
			roleColor
			rolePosition
		}
	}
}

query contributor($id: String!) {
	credits(id: $id) {
		user {
			id
		}
	}
}
