fragment metadataFields on PresenceMetadata {
	author {
		name
		id
	}
	altnames
	logo
	thumbnail
	service
	color
	url
	warning
	tags
	description
	button
	category
}
fragment defaultFields on Presence {
	metadata {
		...metadataFields
	}
	users
}

query presences($start: Int, $limit: Int, $query: String) {
	presences(start: $start, limit: $limit, query: $query) {
		...defaultFields
	}
}

query presence($service: StringOrStringArray!) {
	presences(service: $service) {
		users
		metadata {
			...metadataFields
			version
			contributors {
				name
				id
			}
		}
	}
}

query fetchUserChip($id: String!) {
	credits(id: $id) {
		user {
			name
			avatar
			roleColor
		}
	}
}

query userPage($id: String!) {
	credits(id: $id) {
		user {
			name
			avatar
		}
	}
	authorPresences: presences(author: $id) {
		...defaultFields
	}
	contributorPresences: presences(contributor: $id) {
		...defaultFields
	}
}
