name: Build pd
on:
  push:
    tags:
      - "pd-v*"
permissions:
  packages: write
jobs:
  build:
    name: Build pd
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: premid/premid/.github/actions/build-and-push-docker@monorepo
        with:
          app: pd
          token: ${{ secrets.GITHUB_TOKEN }}
